-- VHDL Entity MIPS.MIPS_tester.interface
--
-- Created:
--          by - kolaman.UNKNOWN (KOLAMAN-PC)
--          at - 09:22:44 17/02/2013
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2011.1 (Build 18)
--
LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
USE IEEE.STD_LOGIC_ARITH.ALL;

ENTITY MIPS_tester IS
   PORT(  
		-- Output important signals 
		BPADD     : out std_logic_vector(7 downto 0);
		reset,clock : out std_logic;
		CLKCNT    : in std_logic_vector(15 downto 0);
		STCNT, FHCNT   : in std_logic_vector(7 downto 0);
		ST_TRIGGER	   : in std_logic;
		--------- pipeline lvl0   IF---------
		IF_PC_out								: in  STD_LOGIC_VECTOR( 9 DOWNTO 0 );
		IF_INSTUCTION_out 					: in 	STD_LOGIC_VECTOR( 31 DOWNTO 0 );
		IF_PC_SRC_OUT							: in	STD_LOGIC;
		--------- pipeline lvl1   ID---------
		ID_INSTUCTION_out 					: in 	STD_LOGIC_VECTOR( 31 DOWNTO 0 );
		ID_read_data_1_out					: in 	STD_LOGIC_VECTOR( 31 DOWNTO 0 );
		ID_read_data_2_out					: in 	STD_LOGIC_VECTOR( 31 DOWNTO 0 );
		ID_write_data_out 					:  	STD_LOGIC_VECTOR( 31 DOWNTO 0 );
		ID_SIGN_EXT_OUT						: in 	STD_LOGIC_VECTOR( 31 DOWNTO 0 );
		ID_Regwrite_out						: in 	STD_LOGIC;
		--------- pipeline lvl2   EXE---------
		EXE_INSTUCTION_out 					: in 	STD_LOGIC_VECTOR( 31 DOWNTO 0 );
		EXE_ALU_result_out					: in 	STD_LOGIC_VECTOR( 31 DOWNTO 0 );
		EXE_AINPUT_OUT						: in 	STD_LOGIC_VECTOR( 31 DOWNTO 0 );
		EXE_BINPUT_OUT						: in 	STD_LOGIC_VECTOR( 31 DOWNTO 0 );
		EXE_MUX_AINPUT_OUT					: in 	STD_LOGIC_VECTOR( 1 DOWNTO 0 );
		EXE_MUX_BINPUT_OUT					: in 	STD_LOGIC_VECTOR( 1 DOWNTO 0 );
		EXE_Zero_out						: in 	STD_LOGIC;
		EXE_MUX_ADRESS_OUT					: in 	STD_LOGIC_VECTOR( 4 DOWNTO 0 );
		--------- pipeline lvl3   DMEM---------
		DM_INSTUCTION_out 					: in 	STD_LOGIC_VECTOR( 31 DOWNTO 0 );
		DM_MEM_WRITE  						: in 	STD_LOGIC;
		DM_WRITE_DATA                       : in 	STD_LOGIC_VECTOR( 31 DOWNTO 0 );
		DM_READ_DATA                        : in 	STD_LOGIC_VECTOR( 31 DOWNTO 0 );
		DM_MEM_ADDRESS						: in 	STD_LOGIC_VECTOR( 9 DOWNTO 0 );
		
		--------- pipeline lvl4   WB---------
		WB_INSTUCTION_out,WB_write_data_out	: in 	STD_LOGIC_VECTOR( 31 DOWNTO 0 );
		WB_REGWRITE							: in 	STD_LOGIC;
		WB_JAL_OUT							: in 	STD_LOGIC
		

   );

-- Declarations

END MIPS_tester ;

--
-- VHDL Architecture MIPS.MIPS_tester.struct
--
-- Created:
--          by - kolaman.UNKNOWN (KOLAMAN-PC)
--          at - 09:22:44 17/02/2013
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2011.1 (Build 18)
--
LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
USE IEEE.STD_LOGIC_ARITH.ALL;


ARCHITECTURE struct OF MIPS_tester IS

   -- Architecture declarations

   -- Internal signal declarations


   -- ModuleWare signal declarations(v1.9) for instance 'U_0' of 'clk'
   SIGNAL mw_U_0clk : std_logic;
   SIGNAL mw_U_0disable_clk : boolean := FALSE;

   -- ModuleWare signal declarations(v1.9) for instance 'U_1' of 'pulse'
   SIGNAL mw_U_1pulse : std_logic :='0';


BEGIN

	BPADD <= "00111000";
	
	
	
	
   -- ModuleWare code(v1.9) for instance 'U_0' of 'clk'
   u_0clk_proc: PROCESS
   BEGIN
      WHILE NOT mw_U_0disable_clk LOOP
         mw_U_0clk <= '0', '1' AFTER 50 ns;
         WAIT FOR 100 ns;
      END LOOP;
      WAIT;
   END PROCESS u_0clk_proc;
   mw_U_0disable_clk <= TRUE AFTER 100000000 ns;
   clock <= mw_U_0clk;

   -- ModuleWare code(v1.9) for instance 'U_1' of 'pulse'
   reset <= mw_U_1pulse;
   u_1pulse_proc: PROCESS
   BEGIN
      mw_U_1pulse <= 
         '0',
         '1' AFTER 20000 ps,
         '0' AFTER 120000 ps,
		 '1' after 2000000 ps,
		 '0' after 2050000 ps;
      WAIT;
    END PROCESS u_1pulse_proc;

   -- Instance port mappings.

END struct;
